// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6HWD68wWIzmKk-_Iy4no25OrGMlxqfY',
    appId: '1:643185961076:web:c31881704f5640c7f98921',
    messagingSenderId: '643185961076',
    projectId: 'app-login-5decd',
    authDomain: 'app-login-5decd.firebaseapp.com',
    storageBucket: 'app-login-5decd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPfr9pXvZhVyNj1hVSh7HUtFWvsI-FzzY',
    appId: '1:643185961076:android:00b30497dab97acff98921',
    messagingSenderId: '643185961076',
    projectId: 'app-login-5decd',
    storageBucket: 'app-login-5decd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ6HWD68wWIzmKk-_Iy4no25OrGMlxqfY',
    appId: '1:643185961076:web:3094e3e10af0105af98921',
    messagingSenderId: '643185961076',
    projectId: 'app-login-5decd',
    authDomain: 'app-login-5decd.firebaseapp.com',
    storageBucket: 'app-login-5decd.firebasestorage.app',
  );
}
